fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        exclude: resources.py
        language_version: python3.10

  #- repo: https://github.com/pycqa/flake8
  #  rev: 6.1.0
  #  hooks:
  #  - id: flake8
  #    args:
  #      - --ignore=E203,E402,E501,W291,W503
  #      - --max-line-length=200

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: flake8-check1 # stop the build if there are Python syntax errors or undefined names
        name: flake8-check1
        entry: flake8 eqip --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=*exclude*
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: flake8-check2  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        name: flake8-check2
        entry: flake8 eqip --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=*exclude*
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: compile-qt-resources
        name: compile-qt-resources
        entry: pyrcc5 -o resources.py resources.qrc
        language: system
        pass_filenames: false
        always_run: true